name: Docker-Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Docker-Publish:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
          brew install --cask docker docker-machine

        # secrets: DOCKER_USER, DOCKER_TOKEN
      - name: Build & Publish
        run: |
          image=${GITHUB_REPOSITORY#*/}:${GITHUB_REF#refs/*/}
          docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
          docker image build -t $image .
          docker tag $image ${{secrets.DOCKER_USER}}/$image
          docker push ${{secrets.DOCKER_USER}}/$image
